name: Publish devcontainer container
on:
  push:
    paths:
      - 'Dockerfile'

jobs:
  build:
    name: Update devcontainer container
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v1
        with:
          registry: docker.pkg.github.com
          repository: mcolyer/monalisa
          username: $GITHUB_ACTOR
          password: ${{ secrets.GITHUB_TOKEN }}
          tags: latest
